services:
  web:
    build: ./web
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      Services:AiServiceUrl: http://ai:7000
      Services:DatabaseUrl: mongodb://db:27017
  ai:
    build: ./ai
    stop_signal: SIGINT
    environment:
      DatabaseUrl: mongodb://db:27017
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  db:
    image: mongo:8.0.0-rc13-jammy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
