name: ai_env
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - pip
  - python==3.10
  - pytorch==2.4.0
  - torchaudio==2.4.0
  - torchvision==0.19.0
  - pytorch-cuda=12.4
  - flask==3.0.3
  - pypdf==4.3.1
  - colorama==0.4.6
  - waitress=3.0.0
  - chromadb==0.5.0
  - Werkzeug==3.0.3
  - requests==2.32.3
  - langchain==0.2.15
  - beautifulsoup4==4.12.3
  - langchain-core==0.2.36
  - langchain-chroma==0.1.3
  - langchain-community==0.2.14
  - langchain-huggingface==0.0.3
  - cryptography==43.0.0
  - conda-forge::transformers==4.43.1
  - conda-forge::sentence-transformers==3.0.1
  - conda-forge::pymongo=4.8.0
  - conda-forge::dacite=1.8.1
  - pip:
      - ollama==0.3.2
      - huggingface-hub==0.24.0
